# Generated by Django 6.0.1 on 2026-02-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_choice_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
